<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>AMANC_Inventory</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\LogoAMANC.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />
    <PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\LogoAMANC.png" />
  </ItemGroup>

</Project>
